#!/bin/bash

copy_cpp() {
    local cpp_file=$1
    python3 ./kyopro_library/kyopro_tools/exp.py -r $cpp_file

    if [ $2 == "true" ]; then
        python3 ./atcoder/ac-library/expander.py combined.cpp
    fi

    # combined.cpp の末尾に元のファイル名をコメントとして付け加える
    echo "//$cpp_file" >> combined.cpp

    # ベース名と拡張子を分ける
    local basename="${cpp_file%.*}"
    local extension="${cpp_file##*.}"
    
    # 同名ファイルのカウントを取得し、新しい連番を作成
    local counter=$(ls esc/"$basename"*.$extension 2>/dev/null | wc -l)
    counter=$((counter + 1))
    
    # 新しいファイル名を作成
    local new_filename="$basename$(printf "%02d" "$counter").$extension"
    
    # ファイルをコピー
    cp "$cpp_file" "esc/$new_filename"
    echo "Copied $cpp_file to esc/$new_filename"
}

# メインロジック
if [ -z "$1" ]; then
    echo "Usage: $0 <filename (with or without .cpp)> [t]"
    exit 1
fi

# 拡張子の自動補完ロジック
# ${1%.cpp} は、「もし末尾が .cpp ならそれを取り除く」という意味
# その後に .cpp を付け直すことで、二重付与を防ぎつつ補完する
cpp_file="${1%.cpp}.cpp"

# tオプションが指定された場合はACLをexpandする
if [ "$2" == "t" ]; then
    acl_flag="true"
else
    acl_flag="false"
fi

copy_cpp $cpp_file $acl_flag

pbcopy<combined.cpp
